# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


 development:
  FACEBOOK_KEY: '221244558287635'
  FACEBOOK_SECRET: '5ed3f137a806bee3eedb5a7082c066a4'
  GMAIL_KEY: 'rubykh12345@gmail.com'
  GMAIL_SECRET: 'kh@ruby12345'
  BRAINTREE_MERCHANT_ID: 'sc5njkdv63cpg6b3'
  BRAINTREE_PUBLIC_KEY: '9czbsrcw763b33dp'
  BRAINTREE_PRIVATE_KEY: 'd30a57124af1b80ebe3b2d8443cb33ea'