# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1c1eb2ef4ddb5a80a6d67b47f797ed0dcb9f4c1930c2a425d9db3ec0ddc9c50089ff7fc8c19ef228d74109e39f1427ca1954a83d5194e6f4b7427a6c0d97275

test:
  secret_key_base: 265f24395e6f7d5b069e5ce2a5fe3a72f0d2c333715366f2d63b5f207adfa925345e36cd36ba24b8c1a098d48b504c4586da95d8dc1c79f7b634e2f55432454f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
